import { Project, TeamMember } from './types';

export const PROJECTS: Project[] = [
  {
    id: 'casa-magoito',
    title: 'Casa no Magoito',
    location: 'Sintra, Portugal',
    year: '2014-2024',
    description: 'Uma habitação unifamiliar que se estende sobre a falésia do Magoito. O projeto explora a horizontalidade e a relação tátil com a paisagem através de uma sequência de pátios e planos de betão que protegem e enquadram o Atlântico.',
    fullDescription: 'A casa está implantada no extremo sul do terreno, procurando o horizonte aberto sobre o vale e a Praia do Magoito. Dessa forma, o restante espaço permanece livre, entregue ao desenho da paisagem e à continuidade natural do lugar.\n\nSobre um embasamento comum erguem-se quatro volumes dispostos longitudinalmente no sentido nascente/poente. Com coberturas de duas águas e dimensões distintas, moldadas pelas necessidades do programa, evocam a imagem de quatro pequenas casas que, ao aproximarem-se e fundirem-se entre si, constroem uma só entidade: a Casa.',
    technicalSpecs: '**Arquitectura:** Edgeline Arquitectos Associados | **Equipa de projecto:** Alexandre Berardo, Gonçalo Castro, Rita Serra Fernandes, Vanessa Pícaro | **Área de construção:** 190 m2 | **Localização:** Magoito – Sintra | **Fotografia:** Edgeline',
    coverImage: 'https://lh3.googleusercontent.com/d/1pqQF_ouWzYkKo-8oM6c7U5-W8odhs6wb',
    images: [
      'https://lh3.googleusercontent.com/d/1W1HKZKKU7K8q4614EI5A3vsFNrnlwLA8',
      'https://lh3.googleusercontent.com/d/1m3YxIQ-dXXezTxXz2SIRIyYu7lU_BLk_',
      'https://lh3.googleusercontent.com/d/1umBwCXHOxT2RW61h4lLI-VCcJQjBctUd',
      'https://lh3.googleusercontent.com/d/1lzwePs2qwE06f_RYC12idwmEKkSSjOaW',
      'https://lh3.googleusercontent.com/d/1Rx8HSYf_WGNvXMzmvprO8Kficix9KWlM',
      'https://lh3.googleusercontent.com/d/1pqQF_ouWzYkKo-8oM6c7U5-W8odhs6wb',
      'https://lh3.googleusercontent.com/d/1i9XHCcniF1zwwLzeX1qOu4LUG9KBLiwc',
      'https://lh3.googleusercontent.com/d/1qtXiIetcLzpoZ3d4vYSowqsaDW1LhCTc',
      'https://lh3.googleusercontent.com/d/1KCAdnA-WBBdOwBttPH3THhEL5C0NX3l4',
      'https://lh3.googleusercontent.com/d/1bXO1T_DofYhMaHk8LnrLBXLCClp7OOOX',
      'https://lh3.googleusercontent.com/d/1zDYW3fiO4GSj9zztLAZJHMfOxY01cOud',
      'https://lh3.googleusercontent.com/d/1Chaf1EiJl_TkKQDSx6NagtvR-0gixJ6i',
      'https://lh3.googleusercontent.com/d/1Rx9OWbdJbNkqhG7bIytqvuS7zmJczoKb',
      'https://lh3.googleusercontent.com/d/1mFUUJyBU2EFwqSx0D2rdp6IGklhE6pNd',
    ],
    featured: true,
  },
  {
    id: 'pestana-lisboa-vintage',
    title: 'Pestana Lisboa Vintage',
    location: 'Rua Braamcamp, 7 - Lisboa',
    year: '2015 - 2021',
    description: 'O Pestana Lisboa Vintage resulta da reabilitação e ampliação de um edifício dos anos 50 do século XX, projectado pelo arquitecto Sérgio Gomes. A intervenção preserva integralmente as fachadas existentes, acrescentando apenas um novo piso na cobertura revestido a zinco, de linguagem contemporânea e discretamente integrado - uma arquitectura que procura a contenção e a ausência de ruído.',
    fullDescription: 'O Pestana Lisboa Vintage resulta da reabilitação e ampliação de um edifício dos anos 50 do século XX, projectado pelo arquitecto Sérgio Gomes. A intervenção preserva integralmente as fachadas existentes, acrescentando apenas um novo piso na cobertura revestido a zinco, de linguagem contemporânea e discretamente integrado - uma arquitectura que procura a contenção e a ausência de ruído.\n\nConcebido como um hotel de 108 suites, o projecto concilia memória arquitectónica, conforto e funcionalidade no centro de Lisboa.',
    technicalSpecs: '**Arquitectura:** Edgeline Arquitectos Associados | **Equipa de projecto:** Alexandre Berardo, Gonçalo Castro, Rita Serra Fernandes, Alexandre Silva Fernandes | **Decoração:** Dueto – Jaime Morais | **Área de construção:** 5 890 m2 | **Localização:** Lisboa | **Fotografia:** Rodrigo Cabral, Edgeline, PHG',
    coverImage: 'https://lh3.googleusercontent.com/d/1GiQxGOzYwq6boDlb6K7-lrobAPokAkBZ',
    images: [
      'https://lh3.googleusercontent.com/d/1pszjLndK952ieJYDrHJrpU49lU8fpCwh',
      'https://lh3.googleusercontent.com/d/1DGevnXwSz-9Br9ztj-x54_ncZDha-CRi',
      'https://lh3.googleusercontent.com/d/1hPw2jMAR--5jerUplXWnziY58vcdEvwI',
      'https://lh3.googleusercontent.com/d/1Z-4ohGu5vIx78l6jKGjiYps8Xq7K9it4',
      'https://lh3.googleusercontent.com/d/1VsBCPxdK4XoFXgz-nTvzNLHu1s6ela4V',
      'https://lh3.googleusercontent.com/d/1GiQxGOzYwq6boDlb6K7-lrobAPokAkBZ',
      'https://lh3.googleusercontent.com/d/1oZQrm9cEEV9dRuYMGxtbcbWwdRcvVnwq',
      'https://lh3.googleusercontent.com/d/1bNMM6HsJYn_lG5trSxmZpQSU3weZ6Gob',
      'https://lh3.googleusercontent.com/d/1jICiEW5ws7snEBdyRMm9c2ghntDPaz_Z',
      'https://lh3.googleusercontent.com/d/15mbNCRBJecwI91UiXeOxXLlk5y1IE7j4',
      'https://lh3.googleusercontent.com/d/1GwJGaLhJtjA1D0uWzXTH4uw9Lz1n1cbA',
    ],
    featured: true,
  },
  {
    id: 'edificio-portico',
    title: 'Edifício Pórtico',
    location: 'Lisboa, Portugal',
    year: 2022,
    description: 'Reabilitação urbana centrada na preservação da memória industrial. O novo volume em vidro e aço dialoga com a alvenaria original, estabelecendo um novo ritmo visual na rua.',
    coverImage: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=2070',
    images: [
      'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=2070',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=2070',
    ],
    featured: true,
  },
  {
    id: 'pavilhao-e',
    title: 'Pavilhão E',
    location: 'Porto, Portugal',
    year: 2024,
    description: 'Um espaço de exposição temporária que explora a efemeridade e a transparência. A malha modular permite diferentes configurações, adaptando-se às diversas obras de arte.',
    coverImage: 'https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&q=80&w=2070',
    images: [
      'https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&q=80&w=2070',
      'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&q=80&w=2070',
    ],
    featured: true,
  },
  {
    id: 'atelier-cascais',
    title: 'Atelier Cascais',
    location: 'Cascais, Portugal',
    year: 2021,
    description: 'O próprio espaço de trabalho do atelier. Uma reflexão sobre a prática da arquitetura, onde a simplicidade dos materiais permite o foco no processo criativo.',
    coverImage: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&q=80&w=2070',
    images: [
      'https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&q=80&w=2070',
    ],
    featured: false,
  },
  {
    id: 'residencia-viana',
    title: 'Residência Viana',
    location: 'Viana do Castelo, Portugal',
    year: 2023,
    description: 'Um diálogo entre a pedra local e o vidro. A casa organiza-se em torno de um pátio central que protege da nortada e convida a luz.',
    coverImage: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&q=80&w=2070',
    images: [
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&q=80&w=2070',
    ],
    featured: true,
  },
  {
    id: 'biblioteca-m',
    title: 'Biblioteca M',
    location: 'Braga, Portugal',
    year: 2024,
    description: 'Espaço público focado na acústica e na luz zenital. O uso de madeira clara cria uma atmosfera de concentração e calma.',
    coverImage: 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&q=80&w=2070',
    images: [
      'https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&q=80&w=2070',
    ],
    featured: true,
  },
];

export const TEAM: TeamMember[] = [
  {
    id: 'alexandre-berardo',
    name: 'Alexandre Berardo',
    role: 'Principal',
    bio: 'Nascido em Lisboa em 1977.\n\nLicenciado em Arquitectura pela Universidade Lusíada em 1999.',
    longBio: 'Distinguido pela Universidade Lusíada com o prémio de Melhor Classificação da Licenciatura em Arquitectura 1999, iniciou a sua actividade profissional nesse mesmo ano na M.A. Silva Fernandes Arquitectos, sob a direcção do Arq. Manuel Silva Fernandes, onde colaborou até 2000.\n\nEntre 2000 e 2009 integrou a equipa da Gonçalo Byrne Arquitectos, participando no desenvolvimento e coordenação de diversos projectos e obras, com especial incidência na recuperação e reabilitação de património edificado. Destacam-se, neste período, as intervenções no ISEG - Convento das Inglesinhas, em Lisboa, e na Pousada do Palácio de Estoi, no Algarve.\n\nEntre 2009 e 2013 exerceu actividade como arquitecto em regime liberal, desenvolvendo projectos em nome próprio e em parceria com diversos ateliers de arquitectura, entre os quais Gonçalo Byrne Arquitectos, Opera Projects, Jag Arquitectos, Pedro Berardo e Ceregeiro – Arquitectura Paisagista.\n\nEm 2014 fundou em Lisboa a edgeline arquitectos associados, lda., sociedade de arquitectura da qual é sócio-gerente, responsável pela coordenação e gestão dos projectos e obras.',
    photo: 'https://lh3.googleusercontent.com/d/1rHgHTKyBWyb8Oq89clKTSqbgpqxJs8J5',
  },
  {
    id: 'joao-gois',
    name: 'João Gois',
    role: 'Associado',
    bio: 'Nascido em Lisboa em 1972.\n\nLicenciado em Arquitectura pela Universidade Lusíada em 1999.',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=1974',
  },
  {
    id: 'goncalo-castro',
    name: 'Gonçalo Castro',
    role: 'Gestor de Projecto',
    bio: 'Nascido em Lisboa em 1971.\n\nLicenciado em Arquitectura pela Universidade Técnica de Lisboa em 1995.',
    photo: 'https://lh3.googleusercontent.com/d/1FlTprnHinZ3e-qumX9oL4Gxn-L5w4Idq',
  },
  {
    id: 'doriana-santos',
    name: 'Doriana Santos',
    role: 'Gestora de Projecto',
    bio: 'Nascida em Coimbra em 1977\n\nLicenciada em Arquitectura pela Universidade de Coimbra em 2002',
    photo: 'https://lh3.googleusercontent.com/d/1TmtR9qrGtvvBMsrSSM_p3u4qkLB1xvJi',
  },
  {
    id: 'rita-serra',
    name: 'Rita Serra',
    role: 'Gestora de Projecto',
    bio: 'Nascida em Lisboa em 1982.\n\nLicenciada em Arquitectura pela Universidade Lusíada em 2005.',
    photo: 'https://lh3.googleusercontent.com/d/1S60OXa9N8LLqYjouHzlnOLCsspIBBaAZ',
  },
];
